
/**
 * Email template: New submission received (Owner)
 * Sent when a proxy submits photos for any milestone.
 */
export function submissionReceivedEmail({
  ownerName,
  projectName,
  milestoneName,
  submitterName,
  hasAiFlagged,
  projectUrl,
}: {
  ownerName: string
  projectName: string
  milestoneName: string
  submitterName: string
  hasAiFlagged: boolean
  projectUrl: string
}): string {
  const flagBanner = hasAiFlagged
    ? `<div style="background:#fce8e6;border-left:4px solid #c5221f;padding:12px 16px;margin:16px 0;border-radius:4px;">
        <strong style="color:#c5221f;">⚠ AI Analysis Flagged Concerns</strong>
        <p style="margin:4px 0 0;color:#3c4043;font-size:14px;">The AI inspection has identified items that warrant your attention. Review the full report on your dashboard.</p>
       </div>`
    : `<div style="background:#e6f4ea;border-left:4px solid #137333;padding:12px 16px;margin:16px 0;border-radius:4px;">
        <strong style="color:#137333;">✓ AI Analysis Complete</strong>
        <p style="margin:4px 0 0;color:#3c4043;font-size:14px;">Inspection report generated. No critical concerns flagged.</p>
       </div>`

  return `
    <div style="font-family:Inter,sans-serif;max-width:600px;margin:0 auto;color:#1f2937;">
      <div style="background:#0F6D4E;padding:24px;border-radius:12px 12px 0 0;">
        <h1 style="color:white;margin:0;font-size:22px;">BuildWatch</h1>
        <p style="color:rgba(255,255,255,0.8);margin:4px 0 0;font-size:14px;">Construction Progress Update</p>
      </div>
      <div style="background:white;border:1px solid #e5e7eb;border-top:none;padding:32px;border-radius:0 0 12px 12px;">
        <p style="color:#374151;">Hi ${ownerName},</p>
        <p style="color:#374151;">A new progress submission has been received for <strong>${projectName}</strong>.</p>
        <table style="width:100%;border-collapse:collapse;margin:16px 0;">
          <tr><td style="padding:8px 0;color:#6b7280;font-size:14px;width:140px;">Submitted by</td><td style="padding:8px 0;font-weight:600;">${submitterName}</td></tr>
          <tr><td style="padding:8px 0;color:#6b7280;font-size:14px;">Milestone</td><td style="padding:8px 0;font-weight:600;">${milestoneName}</td></tr>
        </table>
        ${flagBanner}
        <a href="${projectUrl}" style="display:inline-block;background:#0F6D4E;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin-top:8px;">Review Submission →</a>
        <hr style="border:none;border-top:1px solid #e5e7eb;margin:32px 0;">
        <p style="color:#9ca3af;font-size:12px;">You are receiving this because you are the project owner on BuildWatch. This report was generated by AI from photographic submissions and does not constitute a professional structural or engineering assessment.</p>
      </div>
    </div>
  `
}

/**
 * Email template: Milestone approved (Contractor)
 * Sent when the owner approves a milestone.
 */
export function milestoneApprovedEmail({
  contractorName,
  projectName,
  milestoneName,
  approvedByName,
  nextMilestoneName,
  projectUrl,
}: {
  contractorName: string
  projectName: string
  milestoneName: string
  approvedByName: string
  nextMilestoneName?: string
  projectUrl: string
}): string {
  const nextSection = nextMilestoneName
    ? `<div style="background:#e6f4ea;border-left:4px solid #137333;padding:12px 16px;margin:16px 0;border-radius:4px;">
        <strong style="color:#137333;">Next Phase Unlocked</strong>
        <p style="margin:4px 0 0;color:#3c4043;font-size:14px;">${nextMilestoneName} is now active.</p>
       </div>`
    : ''

  return `
    <div style="font-family:Inter,sans-serif;max-width:600px;margin:0 auto;color:#1f2937;">
      <div style="background:#0F6D4E;padding:24px;border-radius:12px 12px 0 0;">
        <h1 style="color:white;margin:0;font-size:22px;">BuildWatch</h1>
        <p style="color:rgba(255,255,255,0.8);margin:4px 0 0;font-size:14px;">Milestone Approved</p>
      </div>
      <div style="background:white;border:1px solid #e5e7eb;border-top:none;padding:32px;border-radius:0 0 12px 12px;">
        <p>Hi ${contractorName},</p>
        <p>The project owner <strong>${approvedByName}</strong> has approved the following milestone for <strong>${projectName}</strong>:</p>
        <div style="background:#f9fafb;padding:16px;border-radius:8px;margin:16px 0;text-align:center;">
          <p style="font-size:18px;font-weight:700;color:#0F6D4E;margin:0;">✓ ${milestoneName}</p>
        </div>
        ${nextSection}
        <a href="${projectUrl}" style="display:inline-block;background:#0F6D4E;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin-top:8px;">View Project →</a>
      </div>
    </div>
  `
}

/**
 * Email template: Heartbeat silence alert (Owner)
 * Sent when no proxy submission has been received for 3+ days.
 */
export function silenceAlertEmail({
  ownerName,
  projectName,
  daysSinceLastSubmission,
  projectUrl,
}: {
  ownerName: string
  projectName: string
  daysSinceLastSubmission: number
  projectUrl: string
}): string {
  return `
    <div style="font-family:Inter,sans-serif;max-width:600px;margin:0 auto;color:#1f2937;">
      <div style="background:#b45309;padding:24px;border-radius:12px 12px 0 0;">
        <h1 style="color:white;margin:0;font-size:22px;">BuildWatch</h1>
        <p style="color:rgba(255,255,255,0.8);margin:4px 0 0;font-size:14px;">Site Activity Alert</p>
      </div>
      <div style="background:white;border:1px solid #e5e7eb;border-top:none;padding:32px;border-radius:0 0 12px 12px;">
        <p>Hi ${ownerName},</p>
        <p>No progress photos have been submitted for <strong>${projectName}</strong> in the last <strong>${daysSinceLastSubmission} days</strong>.</p>
        <p style="color:#6b7280;">This could mean your site proxy hasn't visited the site, or they may need a reminder to submit their update through BuildWatch.</p>
        <a href="${projectUrl}" style="display:inline-block;background:#b45309;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin-top:8px;">Chase Your Proxy →</a>
        <hr style="border:none;border-top:1px solid #e5e7eb;margin:32px 0;">
        <p style="color:#9ca3af;font-size:12px;">You are receiving this heartbeat alert because no activity was detected on this project. Alerts trigger after 3 days of inactivity.</p>
      </div>
    </div>
  `
}

/**
 * Email template: Chase Proxy (Proxy)
 * Sent when the owner manually triggers a reminder for a submission.
 */
export function chaseProxyEmail({
  proxyName,
  ownerName,
  projectName,
  milestoneName,
  submissionUrl,
}: {
  proxyName: string
  ownerName: string
  projectName: string
  milestoneName: string
  submissionUrl: string
}): string {
  return `
    <div style="font-family:Inter,sans-serif;max-width:600px;margin:0 auto;color:#1f2937;">
      <div style="background:#b45309;padding:24px;border-radius:12px 12px 0 0;">
        <h1 style="color:white;margin:0;font-size:22px;">BuildWatch</h1>
        <p style="color:rgba(255,255,255,0.8);margin:4px 0 0;font-size:14px;">Submission Reminder</p>
      </div>
      <div style="background:white;border:1px solid #e5e7eb;border-top:none;padding:32px;border-radius:0 0 12px 12px;">
        <p>Hi ${proxyName},</p>
        <p>The project owner <strong>${ownerName}</strong> is requesting an update for <strong>${projectName}</strong>.</p>
        <p style="color:#374151;">Current Milestone: <strong>${milestoneName}</strong></p>
        <p style="color:#6b7280;">Please visit the site and submit the required progress photos as soon as possible.</p>
        <a href="${submissionUrl}" style="display:inline-block;background:#b45309;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin-top:16px;">Go to Site Mode →</a>
        <hr style="border:none;border-top:1px solid #e5e7eb;margin:32px 0;">
        <p style="color:#9ca3af;font-size:12px;">This reminder was manually triggered by the project owner using BuildWatch.</p>
      </div>
    </div>
  `
}

/**
 * Email template: Weekly digest (Owner)
 * Sent every Monday morning with a summary of the past week's activity.
 */
export function weeklyDigestEmail({
  ownerName,
  submissionsThisWeek,
  milestonesApprovedThisWeek,
  activeProjectsCount,
  projectDetails,
  projectUrl,
}: {
  ownerName: string
  submissionsThisWeek: number
  milestonesApprovedThisWeek: number
  activeProjectsCount: number
  projectDetails: string[]
  projectUrl: string
}): string {
  const projectsHtml = projectDetails.map(detail => `
    <li style="margin-bottom:8px;color:#374151;">${detail}</li>
  `).join('')

  return `
    <div style="font-family:Inter,sans-serif;max-width:600px;margin:0 auto;color:#1f2937;">
      <div style="background:#0F6D4E;padding:24px;border-radius:12px 12px 0 0;">
        <h1 style="color:white;margin:0;font-size:22px;">BuildWatch</h1>
        <p style="color:rgba(255,255,255,0.8);margin:4px 0 0;font-size:14px;">Weekly Progress Digest</p>
      </div>
      <div style="background:white;border:1px solid #e5e7eb;border-top:none;padding:32px;border-radius:0 0 12px 12px;">
        <p>Hi ${ownerName},</p>
        <p>Here is your BuildWatch summary for the past week:</p>
        
        <div style="display:flex;gap:16px;margin:24px 0;">
          <div style="flex:1;background:#f9fafb;padding:16px;border-radius:8px;text-align:center;">
            <p style="font-size:24px;font-weight:bold;color:#0F6D4E;margin:0;">${submissionsThisWeek}</p>
            <p style="font-size:12px;color:#6b7280;margin:0;">New Submissions</p>
          </div>
          <div style="flex:1;background:#f9fafb;padding:16px;border-radius:8px;text-align:center;">
            <p style="font-size:24px;font-weight:bold;color:#111827;margin:0;">${milestonesApprovedThisWeek}</p>
            <p style="font-size:12px;color:#6b7280;margin:0;">Approved Phases</p>
          </div>
          <div style="flex:1;background:#f9fafb;padding:16px;border-radius:8px;text-align:center;">
            <p style="font-size:24px;font-weight:bold;color:#111827;margin:0;">${activeProjectsCount}</p>
            <p style="font-size:12px;color:#6b7280;margin:0;">Active Projects</p>
          </div>
        </div>

        <h2 style="font-size:16px;font-weight:600;margin:24px 0 12px;">Project Activity</h2>
        <ul style="padding-left:20px;margin:0;">
          ${projectsHtml}
        </ul>

        <a href="${projectUrl}" style="display:inline-block;background:#0F6D4E;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin-top:24px;">Open Dashboard →</a>
      </div>
    </div>
  `
}
