'use client'

import React from 'react'
import { ArrowRight } from 'lucide-react'
import styles from './AIReportPanel.module.css'

export type AIReport = {
  s1_visible: string
  s2_assessment: string
  s2_confidence: 'High' | 'Medium' | 'Low'
  s3_anomalies: string[]
  s4_limitations: string
  s5_reference: string | null
}

type AIReportPanelProps = {
  report: AIReport
  onUploadDrawings?: () => void
  onExportPdf?: () => void
}

export function AIReportPanel({ report, onUploadDrawings, onExportPdf }: AIReportPanelProps) {
  return (
    <div className={styles.panel}>
      <div className={styles.attribution}>
        This report was generated by AI from photographic submissions. It does not constitute a
        professional structural, engineering, or quantity surveying assessment.
      </div>

      {/* S1 */}
      <div className={styles.section}>
        <h4 className={styles.sectionLabel}>What is visible</h4>
        <p className={styles.sectionBody}>{report.s1_visible}</p>
      </div>

      {/* S2 */}
      <div className={styles.section}>
        <h4 className={styles.sectionLabel}>Stage assessment</h4>
        <span className={`${styles.confidenceChip} ${report.s2_confidence === 'High' ? styles.confidenceHigh : report.s2_confidence === 'Medium' ? styles.confidenceMedium : styles.confidenceLow}`}>
          Confidence: {report.s2_confidence}
        </span>
        <p className={styles.sectionBody}>{report.s2_assessment}</p>
      </div>

      {/* S3 */}
      <div className={styles.section}>
        <h4 className={styles.sectionLabel}>Anomalies & concerns</h4>
        {report.s3_anomalies.length > 0 ? (
          <div className={styles.anomalyBox}>
            <ul className={styles.anomalyList}>
              {report.s3_anomalies.map((a, i) => (
                <li key={i} className={styles.anomalyItem}>{a}</li>
              ))}
            </ul>
          </div>
        ) : (
          <p className={styles.sectionBody}>No anomalies detected in this submission.</p>
        )}
      </div>

      {/* S4 */}
      <div className={styles.section}>
        <h4 className={styles.sectionLabel}>Limitations</h4>
        <div className={styles.limitationsBox}>
          <p className={styles.limitationsText}>{report.s4_limitations}</p>
        </div>
      </div>

      {/* S5 */}
      <div className={styles.section}>
        <h4 className={styles.sectionLabel}>Reference comparison</h4>
        {report.s5_reference ? (
          <p className={styles.sectionBody}>{report.s5_reference}</p>
        ) : (
          <div className={styles.referencePlaceholder}>
            <span className={styles.referenceText}>
              Reference comparison not available — no drawings uploaded to this project.
            </span>
            <button type="button" className={styles.uploadLink} onClick={onUploadDrawings}>
              Upload drawings <ArrowRight size={14} />
            </button>
          </div>
        )}
      </div>

      <button type="button" className={styles.exportBtn} onClick={onExportPdf}>
        Export AI Report PDF
      </button>
      <p className={styles.disclaimer}>AI-generated · Not a professional assessment.</p>
    </div>
  )
}
